// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMiCudBiMyoWv-vTTbdqN2N1LQG7KjZBk',
    appId: '1:211618459999:web:24ec36f7e303de10b346ea',
    messagingSenderId: '211618459999',
    projectId: 'smartfactory-59a13',
    authDomain: 'smartfactory-59a13.firebaseapp.com',
    storageBucket: 'smartfactory-59a13.appspot.com',
    measurementId: 'G-LFGGY2JPFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGh_Ij2tgNoXLrFYEUi83wZh-SfciVjLA',
    appId: '1:211618459999:android:377cf459a1ed936ab346ea',
    messagingSenderId: '211618459999',
    projectId: 'smartfactory-59a13',
    storageBucket: 'smartfactory-59a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_N45XJRPw5r82BU__c4yhLrkH2VdpDQI',
    appId: '1:211618459999:ios:197565a19570ed2cb346ea',
    messagingSenderId: '211618459999',
    projectId: 'smartfactory-59a13',
    storageBucket: 'smartfactory-59a13.appspot.com',
    androidClientId: '211618459999-9ef77sbnng6ibo895eus3n335iof6b43.apps.googleusercontent.com',
    iosClientId: '211618459999-kec8bc0l97crbdfdh2ia3ntufh9mu1hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_N45XJRPw5r82BU__c4yhLrkH2VdpDQI',
    appId: '1:211618459999:ios:197565a19570ed2cb346ea',
    messagingSenderId: '211618459999',
    projectId: 'smartfactory-59a13',
    storageBucket: 'smartfactory-59a13.appspot.com',
    androidClientId: '211618459999-9ef77sbnng6ibo895eus3n335iof6b43.apps.googleusercontent.com',
    iosClientId: '211618459999-kec8bc0l97crbdfdh2ia3ntufh9mu1hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFactory',
  );
}
